version: '3'
services:
  api:
    build: .
    command: /usr/local/bin/gunicorn -w 4 -b 0.0.0.0:4000 loggish:app
    ports:
    - "4000:4000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  web:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./loggish-ui/build:/usr/share/nginx/html:ro
    links:
    - api
  redis:
    image: redis
volumes:
  logvolume01: {}
